<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php';
date_default_timezone_set('Asia/Bangkok');

// --------------------- Database Config ---------------------
$host = 'localhost';
$db   = 'guestwifi_db';
$user = 'root';
$pass = '';
$charset = 'utf8mb4';

$dsn = "mysql:host=$host;dbname=$db;charset=$charset";
$options = [
    PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
];

try {
    $pdo = new PDO($dsn, $user, $pass, $options);

    // --------------------- Fetch All Users ---------------------
    $stmt = $pdo->query("SELECT * FROM guest_users");
    $users = $stmt->fetchAll();

    if (empty($users)) {
        echo "No data found.\n";
        exit;
    }

    // --------------------- Folder Config ---------------------
    $folder = 'C:/xampp/htdocs/TEST2/log';
    if (!is_dir($folder)) mkdir($folder, 0777, true);

    // --------------------- Separate Users ---------------------
    $approved = [];
    $rejected = [];

    foreach ($users as $index => $u) {
        $row = [
            'No.'          => $index + 1,
            'First Name'   => $u['first_name'],
            'Last Name'    => $u['last_name'],
            'Email'        => $u['email'],
            'Username'     => $u['username'],
            'MAC Address'  => $u['mac_address'] ?? '',
            'IP Address'   => $u['ip_address'] ?? '',
            'Company'      => $u['company'] ?? '',
            'Device Type'  => $u['device_type'] ?? '',
            'Start Time'   => $u['start_time'] ? date('Y-m-d H:i:s', strtotime($u['start_time'])) : '',
            'Expire Time'  => $u['expire_time'] ? date('Y-m-d H:i:s', strtotime($u['expire_time'])) : '',
            'Status'       => ($u['approved'] == 1 ? 'Approved' : ($u['approved'] == 2 ? 'Rejected' : 'Pending')),
            'Remark'       => $u['remark'],
            'Created At'   => $u['created_at'] ?? '',
        ];

        if ($u['approved'] == 1) {
            $approved[] = $row;
        } elseif ($u['approved'] == 2) {
            $rejected[] = $row;
        }
    }

    // --------------------- Export CSV Function ---------------------
    function exportCsv($filename, $data) {
        if (empty($data)) return false;
        $fp = fopen($filename, 'w');

        // ✅ UTF-8 BOM (ภาษาไทยไม่เพี้ยน)
        fwrite($fp, "\xEF\xBB\xBF");

        // Header
        fputcsv($fp, array_keys($data[0]));

        // Data rows
        foreach ($data as $row) {
            fputcsv($fp, $row);
        }

        fclose($fp);
        return true;
    }

    // --------------------- File Naming ---------------------
    $timestamp = date('Y-m-d_H-i-s');
    $approvedFile = "$folder/guest_users_approved_{$timestamp}.csv";
    $rejectedFile = "$folder/guest_users_rejected_{$timestamp}.csv";

    // --------------------- Export CSV ---------------------
    $approvedExported = exportCsv($approvedFile, $approved);
    $rejectedExported = exportCsv($rejectedFile, $rejected);
    echo "✅ CSV exported successfully.\n";

    // --------------------- Send Email ---------------------
    $mail = new PHPMailer(true);

    try {
        $mail->isSMTP();
        $mail->Host = '192.168.0.90';                   // Mail server ภายใน
        $mail->SMTPAuth = true;
        $mail->Username = 'mktest@rjm-jewelry.com';     // อีเมลผู้ส่ง
        $mail->Password = '123456';                     // รหัสผ่าน
        $mail->SMTPSecure = 'tls';                      // tls, ssl หรือ ''
        $mail->Port = 587;
        $mail->CharSet = 'UTF-8';

        // ✅ Bypass certificate (จำเป็นในบางระบบ)
        $mail->SMTPOptions = [
            'ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true,
            ],
        ];

        $mail->setFrom('mktest@rjm-jewelry.com', 'Guest WiFi System');
        $mail->addAddress('mikrotik@rjm-jewelry.com', 'Admin');

        $mail->isHTML(true);
        $mail->Subject = '(Alert) Guest WiFi Users Log: ' . date('Y-m-d H:i');

        $body = "
            <p>Dear Admin,</p>
            <p>Attached are the latest Guest WiFi users logs, separated by status:</p>
            <ul>
                <li>Approved Users: " . count($approved) . "</li>
                <li>Rejected Users: " . count($rejected) . "</li>
            </ul>
            <p>All users will be cleared automatically 1 day after export.</p>
            <p>This is an automated report generated by the system.</p>
        ";
        $mail->Body = $body;

        if ($approvedExported) $mail->addAttachment($approvedFile);
        if ($rejectedExported) $mail->addAttachment($rejectedFile);

        $mail->send();
        echo "✅ Email sent successfully.\n";
    } catch (Exception $e) {
        echo "⚠️ Email error: " . $mail->ErrorInfo . "\n";
    }

    // --------------------- Save Export Timestamp ---------------------
    $timestampFile = $folder . '/last_export_timestamp.txt';
    file_put_contents($timestampFile, time());
    echo "🕓 Export timestamp saved.\n";

} catch (PDOException $e) {
    echo "Database error: " . $e->getMessage() . "\n";
}
?>
